apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-1
    spec:
      containers:
      - name: okd-demo
        image: amitvashist7/hello-openshift:v3
        ports:
        - name: nodejs-port
          containerPort: 8080
      nodeSelector:
        hardware: virtual
        env: prod
