apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 3
  selector:
    app: openshift-get-started
  template:
    metadata:
      labels:
        app: openshift-get-started
    spec:
      containers:
      - name: openshift-get-started
        image: amitvashist7/hello-openshift:v1
        ports:
        - name: node-port
          containerPort: 8080
