apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: okd-demo
    image: amitvashist7/hello-openshift:latest
    ports:
    - name: node-port
      containerPort: 8080
